services:
  server:
    build:
      context: .
    container_name: node_server_site_api
    environment:
      NODE_ENV: production
      DB_HOST: mysql_db_site_api
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: site_api_database
      DB_PORT: 3306
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db_site_api
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: site_api_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: